# URL de conexão (substitua 'nome_do_seu_banco' pelo banco que você criou no Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/javaDB
spring.datasource.username=postgres
spring.datasource.password=polegadas5000

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate / JPA
# update: cria as tabelas se não existirem e atualiza a estrutura sem apagar os dados existentes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Stripe
stripe.api.key = BBBBBBBBBBBBBBBBBBBB
stripe.webhook.secret = AAAAAAAAAAAAAAAAAAAA

stripe.url.success=http://localhost:8080/orders/success
stripe.url.cancel=http://localhost:8080/orders/cancel