CREATE TABLE tb_comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    TEXT,
    moment     TIMESTAMP WITHOUT TIME ZONE,
    product_id BIGINT,
    client_id  BIGINT,
    CONSTRAINT pk_tb_comments PRIMARY KEY (id)
);

ALTER TABLE tb_comments
    ADD CONSTRAINT fk_tb_comments_on_product FOREIGN KEY (product_id) REFERENCES tb_product (id);

ALTER TABLE tb_comments
    ADD CONSTRAINT fk_tb_comments_on_client FOREIGN KEY (client_id) REFERENCES tb_users (id);